### ISSUE TITLE
Создать таблицу tasks со списком дел

### ISSUE THREAD

**Issue by noggatur** [velika12/rpg-management#1]
Колонки:
id
owner_id
title
creation_date
deadline_date
duration
importance [0,9]
will [0,1]
- не хочу
- хочу

status [0, 3]
- активная
- выполнена
- не выполнена
- отложена

Вот, что было раньше
http://polyakovin.ru/current/rpg_management/index.php

**Comment by velika12** [comment]
Решили, что importance тоже имеет только два значения 0 и 1.

**Comment by velika12** [comment]
@noggatur Может быть, не хранить `deadline_date` в базе, раз это значение всё равно считается каждый раз исходя из `creation_date` и `duration`?

**Comment by noggatur** [comment]
@velika12 Да, не надо.
